# Generated by Django 6.0.1 on 2026-01-30 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_review_stars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='stars',
            new_name='rating',
        ),
    ]
